version: '3.9'
services:
  tyk-keycloak-db:
    image: postgres:10.11
    container_name: tyk-keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      DB_DATABASE: keycloak
      PROXY_ADDRESS_FORWARDING: 'true'
    expose:
      - "5432"  
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - tyk
  tyk-keycloak:
    image: quay.io/keycloak/keycloak:21.1.0
    container_name: tyk-keycloak
    environment:
      KC_HTTP_ENABLED: "true"
      KC_DB: postgres
      KC_DB_URL_HOST: tyk-keycloak-db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: keycloak
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    command: start-dev --import-realm --hostname-url=http://tyk-keycloak:8080 
    depends_on:
      - tyk-keycloak-db
    ports:
      - 8001:8080
    volumes:
      - ./keycloak-imports:/opt/keycloak/data/import
    networks:
      - tyk
  tyk-dashboard:
    image: tykio/tyk-dashboard:v4.3
    container_name: tyk-dashboard
    environment:
      - TYK_DB_LICENSEKEY=${TYK_DB_LICENSEKEY}
      - TYK_DB_STORAGE_MAIN_TYPE=postgres
      - TYK_DB_STORAGE_MAIN_CONNECTIONSTRING=user=postgres password=topsecretpassword host=tyk-postgres port=5432 database=tyk_analytics
    depends_on:
      tyk-postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    env_file:
      - ./confs/tyk_analytics.env
    networks:
      - tyk

  tyk-gateway:
    image: tykio/tyk-gateway:v4.3
    container_name: tyk-gateway
    ports:
      - "8080:8080"
    env_file:
      - ./confs/tyk.env
    networks:
      - tyk

  tyk-pump:
    image: tykio/tyk-pump-docker-pub:v1.7
    container_name: tyk-pump
    env_file:
      - ./confs/pump.env
      - ./confs/pump.postgres.env
    depends_on:
      tyk-postgres:
        condition: service_healthy
    networks:
      - tyk

  tyk-redis:
    image: redis
    container_name: tyk-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - tyk

  tyk-postgres:
    image: postgres:latest
    container_name: tyk-postgres

    environment:
      - POSTGRES_DB=tyk_analytics
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=topsecretpassword

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - tyk
  
volumes:
  redis-data:
  postgres-data:

networks:
  tyk:
